jwt:
  subject: banking-auth
  issuer: banking.org
  secret:
    access:
    refresh:

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true

logging:
  level:
    com.example.banking: INFO

banking:

  openapi:
    info:
      title: 'Banking API'
      description: 'This API exposes end-points to manage your funds using virtual cards'
    contact:
      url: 'https://github.com/borjom1/SB-Banking-REST-API'

  cards:
    precision: 2
    limits:
      count: 5
      txn-sum: 500
